### ISSUE TITLE
ward does not build with clang on travis-ci

### ISSUE THREAD

**Issue by markuspf** [gap-system/ward#1]
For some reason the build process of LUA doesn't find the clan binary, maybe it's a PATH propagation problem? Would you mind having a look at that, Reimer?

(here is a log: https://travis-ci.org/markuspf/gap/jobs/53803748)

**Comment by rbehrends** [comment]
Should be fixed now.

**Comment by olexandr-konovalov** [comment]
Thanks - now works.
