### ISSUE TITLE
Update LPeg from 0.11 to 1.0 ?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/ward#16]

**Comment by rbehrends** [comment]
That's not urgent, as the new version is about fixing bugs (that we don't hit) and removing some limitations (that we also don't hit). An upgrade would involve copying over the `SConstruct` we use to build LPeg (the regular build system requires manual configuration).

**Comment by fingolfin** [comment]
@rbehrends So is the LPeg ward uses a stock version, or modified? And if you ignore how LPeg is built: Is 1.0 source compatible? Or are changes needed? What about 0.12?

As it is, Debian Jessie ships 0.12, later Debian versions ship 1.0. It would be great if one could compile ward against a system version of LPeg.
