### ISSUE TITLE
Regression: ward fails on Mac OS X

### ISSUE THREAD

**Issue by fingolfin** [gap-system/ward#41]
Unfortunately PR #40 causes ward to fail on OS X:
```
$ make V=1
CPP="gcc -E" ../../hpcgap/ward/bin/addguards2c -cpp  -I. -I../.. -DHAVE_CONFIG_H   -I/Users/mhorn/Projekte/GAP/gap.github/build/hpcgap/extern/install/gc/include -I/Users/mhorn/Projekte/GAP/gap.github/build/hpcgap/extern/install/libatomic_ops/include -Wall -Wextra -Wshadow -Wno-unused-parameter -Wno-sign-compare -Wno-implicit-fallthrough -Wno-unknown-warning-option -isystem /sw/include -- src/ariths.c > gen/ariths.c
/usr/include/mach/i386/_structs.h:92:18: Syntax error
        __denorm :1,
                 ^
ERROR: Ward failed to parse C source
make: *** [../../Makefile.rules:243: gen/ariths.c] Error 1
make: *** Deleting file 'gen/ariths.c'
```

**Comment by dimpase** [comment]
yes, bitfields got broken for some reason:
```
#define _STRUCT_FP_CONTROL      struct __darwin_fp_control
_STRUCT_FP_CONTROL
{
    unsigned short              __invalid       :1,
                                __denorm        :1,
...
```

**Comment by fingolfin** [comment]
That's a plain bitfield, an ancient C feature.

**Comment by dimpase** [comment]
right; if I read the relevant commit 507ad743c3c791ea1c95f6348d3ebe08b1b738d7 from https://github.com/gap-system/ward/pull/40 correctly, `integer_constant` is not an `expression`...

**Comment by ChrisJefferson** [comment]
Yes, `expression` wasn't the right rule, I want `cond_expression`I think

**Comment by ChrisJefferson** [comment]
Basically, we used to support bitfields of that type, but we required just a constant after the `:`, we couldn't support `unsigned short __valid : 2+2,` (or more complex expressions). I tried switching to `expression`, but it turns out I misread the parser heirachy.
