### ISSUE TITLE
Jenkins build fails on CentOS

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/ward#6]
The latest build (69bcb4982f69000d2c65df384ae466fe4e6c8635) fails on one of the Jenkins slaves running CentOS:

```
+ ./build.sh
  File "./build.sh", line 64
    with open("bin/" + cmd, "w") as cmdfile:
            ^
SyntaxError: invalid syntax
```

**Comment by fingolfin** [comment]
Sounds like an outdated python version? The `with` statement was added in Python 2.5 in 2006. What does `python --version` resp. `python2 --version` say?

**Comment by olexandr-konovalov** [comment]
On this machine, `python` calls 2.7.2 and `python2` calls 2.4.3. But @rbehrends fixed this today already in https://github.com/gap-system/ward/commit/e4bb0ba1939149fb3619fb63e0c7e9dfcd13a199
